# Generated by Django 4.2.3 on 2023-07-11 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_exercise_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exercise',
            table='exercises',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
