# Generated by Django 4.2.3 on 2023-07-11 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_exercise_table_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 11, 17, 1, 55, 80583, tzinfo=datetime.timezone.utc)),
        ),
    ]
