# Generated by Django 4.2.3 on 2023-07-11 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_exercise_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
