# Generated by Django 4.2.3 on 2023-07-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_exercise_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_id',
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
    ]
